### ISSUE TITLE
Enabling Data Connectors

### ISSUE THREAD

**Issue by hacknorris** [Azure/SimuLand#10] opened 2021-06-23 05:17 UTC
Hello - on part two - deployment steps - I'm getting a conflict error on enabling data connectors.  Any insights or how to fix this would be greatly appreciated.  My connector for Office ATP and Microsoft Threat Protection states not support api version.  This is in my commercial test tenant.

Conflict

{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Connector kind 'MicrosoftThreatProtection' is not supported in api-version: '2020-01-01'\"\r\n  }\r\n}"
            },
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Connector kind 'OfficeATP' is not supported in api-version: '2020-01-01'\"\r\n  }\r\n}"
            },
            {
                "code": "Unauthorized",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidLicense\",\r\n    \"message\": \"Missing consent\"\r\n  }\r\n}"
            }
        ]
    }
}

**Comment by Cyb3rWard0g** [comment] 2021-06-23 06:49
Hello @hacknorris ! thank you for the heads-up. I have to do a quick test on that tomorrow morning and get back to you. I wonder if the API names changes recently? I have talked to a few folks in the community and the deployment seemed to work just fine. However, something might have changed. I was reading the API docs, and I can see that those names do not exist there. 

https://docs.microsoft.com/en-us/rest/api/securityinsights/data-connectors/list

**Comment by Cyb3rWard0g** [comment] 2021-06-24 02:12
I just tested it and got the same error message. I just updated Azure-Sentinel2Go project which provides the templates to set up the data connectors:  https://github.com/OTRF/Azure-Sentinel2Go/commit/8f7af5254c1ab581f47155fd808e562de1e2065e

Testing it again now.

**Comment by Cyb3rWard0g** [comment] 2021-06-24 02:42
Yayy! The update worked ;) 

![image](https://user-images.githubusercontent.com/9653181/123194258-2e1ed700-d474-11eb-9d33-5b850b932386.png)

Let me know if it works on your end too please to close this issue.

**Comment by hacknorris** [comment] 2021-06-24 03:11
Thank-you Roberto for the quick fix and reply!!  am out office for a couple of days! will test when i get back this weekend.

Dan

**Comment by Cyb3rWard0g** [comment] 2021-06-24 03:29
OK no worries @hacknorris ! Thank you for letting me know. I ran through the whole deployment and everything deployed properly :) 

![image](https://user-images.githubusercontent.com/9653181/123198235-bc965700-d47a-11eb-8b8d-e670d6206746.png)

Enjoy your time off! Thank you for letting me know and for testing the project. I hope you can get through the whole lab and also let me know what you think about it :) Any feedback is greatly appreciated!

**Comment by hacknorris** [comment] 2021-06-27 23:25
@Cyb3rWard0g  -- thankyou -- also confirming the API specific issue has been resolved.  I have a couple of other errors flagging inconsistently tied to the data connectors (missing consent / invalid license). Shall I close this issue out? or would prefer to tag onto here?

**Closed** 2021-06-28 00:41 UTC
Labels: bug, hotfix worked, waiting for user test

**Comment by gregfoxriver** [comment] 2021-07-22 21:45
@hacknorris did you ever find the root cause on those missing consent/invalid license errors?
